ferdistory7/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.home, name='home'),
    
    path('buku/<str:book_id>', views.buku, name="buku"),
    
]

story9/urls.py
from django.urls import path, include

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.

def home(request):
    return render(request, 'story8/home.html')

def buku(request, book_id):
    try:        
        return JsonResponse(
            {"books":0}
        )
    except:
        return JsonResponse(
            {"books":0}
        )    

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

@login_required(login_url='story9:login')
def home(request):
    return render(request, 'story9/home.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('story9:home')
    else:
        form = UserCreationForm()

    context = {'form' : form}
    return render(request, 'registration/register.html', context)

# def login_view(request):
#     username = request.POST['username']
#     password = request.POST['password']
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         # Redirect to a success page.
#         return redirect('story9:login')
        
#     else:
#         messages.info(request, 'Username or password is incorrect')
#         # Return an 'invalid login' error message.
#     context = {}
#     return render(request, 'story9/login.html', context)

# def register_view(request):
#     pass

def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return redirect('story9:home')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
{% endblock meta %}
{% block content %}
<div class="wrapper col-12">
    <div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
        <div class="accordion col-md-10 p-0 mt-2 accordion-1" id="accor1">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Aktivitas Saat Ini</h2>
                <div class="buttons d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
              <p>#DiRumahSaja</p>
              <ul class="m-0">
                  <li>PJJ</li>
                  <li>Nugas</li>
                  <li>Mendengarkan lagu</li>
              </ul>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-2" id="accor2">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Pengalaman Organisasi / Kepanitiaan</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Organisasi:</p>
                    <ul class="m-0">
                        <li>PSDM - DPM FASILKOM UI - 2019/2020</li>
                   </ul>
                    <p>Kepanitiaan:</p>
                    <ul class="m-0">
                        <li>Editorial Marketing - Compfest XII </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-3" id="accor3">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Prestasi</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <ul class="m-0">
                        <li>Third Place in the UNIB Senior High School And University Indonesian Debate Championship (2019)</li>
                        <li>Second place in the 2017 UNIB South Sumatran Senior High School Math Campionship (2017)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-4" id="accor4">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Contact Me</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0 d-flex flex-column">
                    <div class="d-flex">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/1200px-Instagram_logo_2016.svg.png" height="30" width="30" class="mr-2">
                        <h4><a href="https://www.instagram.com/ferdifdi/">@ferdifdi</a></h4> 
                    </div>
                    <div class="d-flex mt-2">
                        <img src="https://www.stickpng.com/assets/images/58e91afdeb97430e81906504.png" height="30" width="30" class="mr-2">
                        <h4><a href="https://www.linkedin.com/in/ferdifdi/">Ferdi Fadillah</a></h4> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'main/js/behavior.js' %}"></script>
{% endblock content %}

story8/templates/story8/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story8</title>
<meta name="img" content="{% static 'story8/img/' %}">
<meta name="home" content="{% url 'story8:home' %}">
<meta name="csrf" content="{{ csrf_token }}">
<link rel="stylesheet" href="{% static 'story8/css/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">
{% endblock meta %}


{% block content %}
<body class="">
  
  <div class="container px-md-5 py-5 px-3">
    <a href="{% url 'story8:home' %}" class="text-dark text-decoration-none">
    <h2>Search a Book</h2></a>
    <div class="input-group mb-1 col-md-7 px-0">
      <input type="text" class="form-control input-keyword" placeholder="Book's title" aria-label="Book's title"
        aria-describedby="button-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary btn-search text-dark search-button" type="button" id="button-addon2">
          Search
        </button>
      </div>
    </div>
    <div class="d-flex flex-column content">
      <div class="d-flex flex-column justify-content-center col-md-7 mt-5">
      </div>
      <!-- Ajax Content -->
    </div>
  </div>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- Optional JavaScript -->
  <script src="{% static 'story8/js/script.js' %}"></script>
</body>
{% endblock content %}

story9/templates/story9/home.html
{% extends "base.html" %}

{% block content %}

<div class="parent-div d-flex align-items-center justify-content-center">
    <div class="child-div" style="padding: 100px;">
        <h1>This is the home page!</h1>
        {% if user.is_authenticated %}
        <h2>Your name is: {{ user.username }}</h2>
        {% else %}
        <h2>You are not logged in.</h2>
        {% endif %}
    
        <a href="{% url 'story9:logout' %}">
            <button type="button" class="btn btn-light btn-logout">Logout</button>
        </a>
    </div>
</div>  

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block meta %}
    
    {% endblock meta %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>    
    <title>Welcome to Ferdi Story</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <div class="topnav">      

        <div style="float: right;">
            <a href="{% url 'main:home' %}" >Home</a>
        </div>

        <div style="float: right;">
            <a href="{% url 'story8:home' %}" >Story8</a>
        </div>

        <div style="float: right;">
            <a href="{% url 'story9:home' %}" >Story9</a>
        </div>

    </div>

    <!-- navbar bawah -->
    <div class="footer">
        <!-- button ig -->
        <div style="float: right;">
            <a href="https://www.instagram.com/ferdifdi/">
                <img src="{% static 'img/iglogo.png' %}" class="ikon">
            </a>
        </div>
        
        <!-- button linkedin  -->
        <div style="float: right;"> 
            <a href="https://www.linkedin.com/in/ferdifdi/">
                <img src="{% static 'img/linkedinlogo.png' %}" class="ikon">
            </a>
        </div>
    </div>    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>